variableAxisTitleDictionary = {
    "ngElectron":           "Number of Good Electrons",
    "gElectron_pt[0]":      "Leading Electron p_{T} (GeV)",
    "gElectron_eta[0]":     "Leading Electron #eta",
    "gElectron_phi[0]":     "Leading Electron #phi",
    "gElectron_E[0]":       "Leading Electron Energy (GeV)",
    "gElectron_mass[0]":    "Leading Electron Mass (GeV)",
    "gElectron_px[0]":      "Leading Electron p_{x} (GeV)",
    "gElectron_py[0]":      "Leading Electron p_{y} (GeV)",
    "gElectron_pz[0]":      "Leading Electron p_{z} (GeV)",
    "nggenElectron":        "Number of Gen-Matched Electrons",
    "ggenElectron_pt[0]":   "Gen-Matched Electron p_{T} (GeV)",
    "ggenElectron_eta[0]":  "Gen-Matched Electron #eta",
    "ggenElectron_phi[0]":  "Gen-Matched Electron #phi",
    "ggenElectron_E[0]":    "Gen-Matched Electron Energy (GeV)",
}

variableFileNameDictionary = {
    "ngElectron":           "n_good_electrons",
    "gElectron_pt[0]":      "electron_pt",
    "gElectron_eta[0]":     "electron_eta",
    "gElectron_phi[0]":     "electron_phi",
    "gElectron_E[0]":       "electron_E",
    "gElectron_mass[0]":    "electron_mass",
    "gElectron_px[0]":      "electron_px",
    "gElectron_py[0]":      "electron_py",
    "gElectron_pz[0]":      "electron_pz",
    "nggenElectron":        "n_genmatched_electrons",
    "ggenElectron_pt[0]":   "genmatched_electron_pt",
    "ggenElectron_eta[0]":  "genmatched_electron_eta",
    "ggenElectron_phi[0]":  "genmatched_electron_phi",
    "ggenElectron_E[0]":    "genmatched_electron_E",
}

variableSettingDictionary = {
    "ngElectron":           "5,0,5",
    "gElectron_pt[0]":      "50,0,25",
    "gElectron_eta[0]":     "46,-4.6,4.6",
    "gElectron_phi[0]":     "32,-3.2,3.2",
    "gElectron_E[0]":       "50,0,50",
    "gElectron_mass[0]":    "20,0.0,0.002",
    "gElectron_px[0]":      "50,-25,25",
    "gElectron_py[0]":      "50,-25,25",
    "gElectron_pz[0]":      "60,-60,60",
    "nggenElectron":        "5,0,5",
    "ggenElectron_pt[0]":   "50,0,25",
    "ggenElectron_eta[0]":  "46,-4.6,4.6",
    "ggenElectron_phi[0]":  "32,-3.2,3.2",
    "ggenElectron_E[0]":    "50,0,50",
}
